-   id: rumdl-check
    name: rumdl check
    description: Check Markdown files for issues using rumdl.
    entry: rumdl
    language: rust
    types: [markdown]

-   id: rumdl-fix
    name: rumdl fix
    description: Automatically fix Markdown issues using rumdl.
    entry: rumdl
    language: rust
    types: [markdown]
