name: Bug Report
description: Report a bug or incorrect behavior in rumdl
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!

        **Before reporting, please search [existing issues](https://github.com/rvben/rumdl/issues?q=is%3Aissue+label%3Abug) to avoid duplicates.**

  - type: input
    id: version
    attributes:
      label: rumdl version
      description: Run `rumdl version` to get this
      placeholder: "0.0.221"
    validations:
      required: true

  - type: dropdown
    id: install-method
    attributes:
      label: Installation method
      options:
        - cargo install
        - Homebrew
        - mise
        - Pre-built binary
        - Docker
        - Built from source
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: A clear description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Minimal markdown content and commands to reproduce the issue
      placeholder: |
        1. Create a file `test.md` with this content:
        ```markdown
        # Example
        ```
        2. Run `rumdl check test.md`
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened (include any error messages)
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Your rumdl configuration (if relevant)
      render: toml
      placeholder: |
        # .rumdl.toml or pyproject.toml [tool.rumdl] section

  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - macOS
        - Linux
        - Windows
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other context, screenshots, or information
