# Nextest configuration
# https://nexte.st/book/configuration

[profile.default]
# Detect flaky tests and retry them
retries = { backoff = "exponential", count = 2, delay = "1s", max-delay = "10s" }

# Run tests with 2x the number of CPUs
test-threads = "num-cpus"

# Fail fast on first failure in CI
fail-fast = false

# Show failed tests immediately
failure-output = "immediate"

# Show successful tests at the end
success-output = "final"

# Status output level
status-level = "pass"

[profile.ci]

# Skip performance tests in CI (they're flaky due to resource variability)
# Exclude specific integration test binaries and performance-related test functions
default-filter = 'not (package(rumdl) and binary(deeply_nested_lists_performance_test)) and not (package(rumdl) and binary(performance_validation_tests)) and not (package(rumdl) and binary(perf_check)) and not test(/performance|benchmark/)'

# More conservative in CI
test-threads = "num-cpus"

# Always show all output in CI
failure-output = "immediate"
success-output = "immediate"
status-level = "all"

# No retries in CI to catch flaky tests
retries = 0

# Quick profile for development
[profile.quick]

# Skip slow tests and performance tests
default-filter = 'not test(/memory/) and not test(/stress/) and not test(/large/) and not test(/error_propagation/) and not test(/performance/) and not test(/comprehensive/) and not test(/deeply_nested/)'

# Even more parallel execution locally
test-threads = "num-cpus"

# Less verbose output
status-level = "fail"

# Development profile - balance between speed and coverage
[profile.dev]

# Skip the slowest tests but include integration tests
default-filter = 'not test(/error_propagation/) and not test(/deeply_nested/) and not test(/memory/) and not test(/stress/) and not test(/large/) and not test(/performance/) and not test(/perf_check/)'

# Good parallelization for dev machines
test-threads = "num-cpus"

# Show failures immediately
failure-output = "immediate"
status-level = "fail"

# No retries for faster feedback
retries = 0

# Ultra-fast profile for pre-commit hooks
[profile.pre-commit]

# Only run unit tests in lib, skip all integration tests and binaries
default-filter = 'package(rumdl) and kind(lib) and not test(/slow|stress|large|integration|comprehensive|cli|config|advanced|commonmark|consistency|performance|benchmark|parity|error_propagation|deeply_nested|memory/)'

# Maximum parallelism for speed
test-threads = "num-cpus"

# Minimal output for speed
status-level = "fail"
failure-output = "immediate"
success-output = "never"

# No retries to save time
retries = 0

# Fail fast on first failure
fail-fast = true

# Performance testing profile - for scheduled/manual runs
[profile.performance]

# Only run performance and benchmark tests
default-filter = 'test(performance) or test(benchmark) or test(deeply_nested)'

# Run tests serially to reduce noise
test-threads = 1

# Show detailed output
failure-output = "immediate"
success-output = "immediate"
status-level = "all"

# Allow retries for flaky tests
retries = { backoff = "exponential", count = 3, delay = "1s", max-delay = "10s" }

# Don't fail fast - run all performance tests
fail-fast = false
